sudo: required
dist: trusty
services:
- postgresql
language: python
python:
- '2.7'
before_install:
- pip install -U setuptools
- pip install -U pysam
- pip install -U cython
- pip install -U uta_align
script: make test
